import { Food } from './app/shared/models/Food';

export const sample_foods: Food[] = [
  {
    id: '1',
    name: 'Pistachio Croissant',
    cookTime: '15-20',
    price: 3.5,
    favorite: true,
    origins: ['France'],
    stars: 4.8,
    imageUrl: 'assets/food_images/pistachio-croissant.jpg',
    tags: ['Pastry', 'Breakfast'],
  },
  {
    id: '2',
    name: 'Pistachio Eclair',
    cookTime: '20-25',
    price: 4.00,
    favorite: true,
    origins: ['France'],
    stars: 4.8,
    imageUrl: 'assets/pistachio-eclair.jpg',
    tags: ['Pastry', 'Dessert'],
  },
  {
    id: '3',
    name: 'Pistachio Muffin',
    cookTime: '20-25',
    price: 2.0,
    favorite: false,
    origins: ['United States'],
    stars: 4.4,
    imageUrl: 'assets/food_images/pistachio-muffin.jpg',
    tags: ['Bakery', 'Breakfast'],
  },
  {
    id: '4',
    name: 'Pistachio Gelato',
    cookTime: '10-15',
    price: 4.5,
    favorite: true,
    origins: ['Italy'],
    stars: 4.9,
    imageUrl: 'assets/food_images/pistachio-gelato.jpg',
    tags: ['Dessert', 'Gelato'],
  },
  {
    id: '5',
    name: 'Pistachio Choux',
    cookTime: '20-25',
    price: 3.75,
    favorite: true,
    origins: ['France'],
    stars: 4.9,
    imageUrl: 'assets/pistachio-choux.jpg',
    tags: ['Pastry', 'Dessert'],
  },
];
