
export const sample_foods: any[] = [
  {
    id: '1',
    name: 'Croissant cu Fistic',
    preparationTime: '15-20',
    price: 15,
    favorite: true,
    origins: ['Franța'],
    imageUrl: 'assets/food_images/pistachio-croissant.jpg',
    tags: ['Patiserie', 'Mic dejun'],
  },
  {
    id: '2',
    name: 'Ecler cu Fistic',
    preparationTime: '20-25',
    price: 16.50,
    favorite: false,
    origins: ['Franța'],
    imageUrl: 'assets/food_images/pistachio-eclair.jpg',
    tags: ['Patiserie', 'Desert'],
  },
  {
    id: '3',
    name: 'Brioșă cu Fistic',
    preparationTime: '20-25',
    price: 9,
    favorite: false,
    origins: ['SUA'],
    imageUrl: 'assets/food_images/pistachio-muffin.jpg',
    tags: ['Cofetărie', 'Mic dejun'],
  },
  {
    id: '4',
    name: 'Inghețată cu Fistic',
    preparationTime: '10-15',
    price: 17.5,
    favorite: true,
    origins: ['Italia'],
    imageUrl: 'assets/food_images/pistachio-gelato.jpg',
    tags: ['Desert', 'Inghețată'],
  },
  {
    id: '5',
    name: 'Choux cu Fistic',
    preparationTime: '20-25',
    price: 18.99,
    favorite: true,
    origins: ['Franța'],
    imageUrl: 'assets/food_images/pistachio-choux.jpg',
    tags: ['Patiserie', 'Desert'],
  },
  {
    id: '6',
    name: 'Cheesecake cu Fistic',
    preparationTime: '25-30',
    price: 20.50,
    favorite: true,
    origins: ['SUA'],
    imageUrl: 'assets/food_images/pistachio-cheesecake.jpg',
    tags: ['Cofetărie', 'Desert'],
  },
  {
    id: '7',
    name: 'Macaron cu Fistic',
    preparationTime: '15-20',
    price: 12.50,
    favorite: false,
    origins: ['Franța'],
    imageUrl: 'assets/food_images/pistachio-macaron.jpg',
    tags: ['Patiserie', 'Desert'],
  },
  {
    id: '8',
    name: 'Tort cu Fistic',
    preparationTime: '35-40',
    price: 24.99,
    favorite: false,
    origins: ['Franța'],
    imageUrl: 'assets/food_images/pistachio-cake.jpg',
    tags: ['Patiserie', 'Desert'],
  },
];

export const sample_tags: any[] = [
  { name: 'Toate', count: 8 },
  { name: 'Patiserie', count: 4 },
  { name: 'Desert', count: 6 },
  { name: 'Mic dejun', count: 2 },
  { name: 'Cofetărie', count: 3 },
  { name: 'Inghețată', count: 1 },
]